webtalk_init -webtalk_dir C:/Users/Ahmet2/Desktop/School/amr/ExampleSubmission_v2 (3)/Simulation_Files/xsim.dir/cpusyssim/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May 26 20:47:20 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7b46e16d-5437-4f07-8302-7668d6b98c2a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e2aa638e-2e6f-4bc6-89b3-9312ede2142b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "11840 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9096_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1868387246 -regid "" -xml C:/Users/Ahmet2/Desktop/School/amr/ExampleSubmission_v2 (3)/Simulation_Files/xsim.dir/cpusyssim/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Ahmet2/Desktop/School/amr/ExampleSubmission_v2 (3)/Simulation_Files/xsim.dir/cpusyssim/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Ahmet2/Desktop/School/amr/ExampleSubmission_v2 (3)/Simulation_Files/xsim.dir/cpusyssim/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
